apiVersion: 1

datasources:

  - name: InfluxDB-Network-Monitor

    uid: influxdb-network

    type: influxdb

    access: proxy

    url: http://influxdb:8181

    isDefault: true

    jsonData:
      version: SQL
      dbName: network_monitoring
      httpMode: POST
      insecureGrpc: true

    secureJsonData:
      token: ${INFLUX_TOKEN}